
#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

TopicName: "/huaray/image_raw"

# 图像格式
Width: 2592   # 图像宽度，单位 pixels。min: 64 、max: 2592、increment：16
Height: 2048  # 图像高度，单位 pixels。min: 32 、max: 2048、increment：2
OffsetX: 0    # X方向偏置，默认 0。min: 0 、increment：16
OffsetY: 0    # Y方向偏置，默认 0。min: 0 、increment：2

# 触发模式
TrigType: 2       # 0 连续触发, 1 软件触发， 2 外部触发。与枚举类 ETrigType 对应
TriggerDelay: 0.0 # 触发延迟时间，单位 μs，默认 0。min: 0、max: 1000000 (1s)。

# 曝光：参数越大，曝光时间越长，传感器捕获到的光线越多，图像就会越亮。但过长的曝光也可能导致过曝或运动模糊，进而损失图像细节。
# ExposureAuto: 0 # 若为外部触发，该参数无效！0 为 Off(关闭自动曝光，使用用户手动设定的 ExposureTime), 1 为 Once, 2 为 Continues
ExposureTime: 5000.0 # 单位 us，默认 5000。min: 1、max: 1000000 (1s)。

# 增益：参数越大，增益越强，亮度越亮，噪点也越多
# 模拟增益：在信号经过模数转换前就进行放大，能提高低光环境下的信号强度，但同时会放大传感器本身的噪声。
# 数字增益：在数字信号处理阶段对像素值进行调整，主要用于细微的亮度补偿。
GainRaw: 1.0      # 模拟增益，默认 1。min: 1、max: 32
DigitalShift: 0   # 数字增益，默认 0。min: 0、max: 4、increment：1

# 伽马因子：参数越小，图像整体偏亮。适当的伽马调整可以改善图像对比度，使细节更突出，但过大或过小都会影响色彩表现。
Gamma: 0.6 # min: 0、max: 3.99998。默认 0.6

# 亮度：参数越大，图像整体亮度越高，细节部分也更明。需要平衡亮度以避免过曝或暗部细节不足的情况。
Brightness: 50 # 默认 50。min: 0、max: 100、increment：1
# 饱和度：参数越大，图像颜色越饱满鲜艳。过高的饱和度可能使颜色显得不自然，而过低则会使画面显得单调。
Saturation: 50 # 默认 50。min: 0、max: 100、increment：2
